### ISSUE TITLE
The generateBundle hook should be used instead of the onwrite hook.

### ISSUE THREAD

**Issue by javadbat** [RJHwang/rollup-plugin-css-porter#3]
![image](https://user-images.githubusercontent.com/11534875/51478054-9054e880-1d9f-11e9-8170-6eb904b06639.png)

**Comment by rj-hwang** [comment]
Which version of rollup do you use?

**Comment by javadbat** [comment]
"rollup": "^1.1.1",
    "rollup-plugin-css-porter": "^0.2.0",
    "rollup-plugin-node-resolve": "^4.0.0"
    "rollup-plugin-babel": "^4.3.2",
    "rollup-plugin-babel-minify": "^7.0.0"

**Comment by rj-hwang** [comment]
OK, I‘ll check it later.

**Comment by javadbat** [comment]
do you check it?

**Comment by rj-hwang** [comment]
So busy Recently, sorry for that. I had confirmed that this deprecated warning message appears after upgrade to rollup-1.0.0+. I'm working on it ASAP now.

**Comment by rj-hwang** [comment]
Main code change : 
1. follow [RFC: Standardise options and CLI flags #1479](https://github.com/rollup/rollup/issues/1479)
and [Unifying Rollup options](https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32) , since `rollup-0.48.0`, `bundle.write(options)` `options.dest > option.file`, `entry > input`. See https://github.com/RJHwang/rollup-plugin-css-porter/commit/5519c450a2310def22cbd2f1926018adca4c1859.
2. follow [rollup-1.0.0: deprecations #2409](https://github.com/rollup/rollup/pull/2409), use `generateBundle` instead `onwrite`. See https://github.com/RJHwang/rollup-plugin-css-porter/commit/589dc4b824b80cab096009ee493da80fb86b2d9b.

**Comment by rj-hwang** [comment]
Release [1.0.0](https://www.npmjs.com/package/rollup-plugin-css-porter/v/1.0.0) to fix this issue.

Please check it.
